const state={offset:INITIAL_OFFSET,min:-2,max:4,hovered:null,heldSide:null,intentHover:null,exterior:false};
const enemyGrid=document.getElementById('enemyGrid'),playerGrid=document.getElementById('playerGrid'),playerBlock=document.getElementById('playerBlock'),enemyMastEl=document.getElementById('enemyMast'),playerMastEl=document.getElementById('playerMast'),enemyMastPips=document.getElementById('enemyMastPips'),playerMastPips=document.getElementById('playerMastPips'),stage=document.getElementById('combatStage'),svg=document.getElementById('arcOverlay'),weaponInfo=document.getElementById('weaponInfo'),targetInfo=document.getElementById('targetInfo'),aft=document.getElementById('moveAft'),fore=document.getElementById('moveFore'),scale=document.getElementById('trackScale');

function glyphMarkup(type,instance='',small=false){return `<span class="weapon-glyph${small?' small':''}" title="${weapons[type].name}${instance?' '+instance:''}">${weaponGlyphs[type]}${instance?`<span class="weapon-instance">${instance}</span>`:''}</span>`}
function basePipsMarkup(e){return Array.from({length:e.max},(_,i)=>i<e.hp?'♥':'·').join(' ')}
function makeRoom(r,side){const el=document.createElement('div');el.className='room'+(r.weapon?' weapon':'');el.dataset.side=side;el.dataset.id=r.id;el.dataset.col=r.col;el.dataset.row=r.row;const heading=r.weapon?`<div class="weapon-heading">${glyphMarkup(r.weapon,r.instance)}<div><div class="room-title">${r.name}${r.instance?` ${r.instance}`:''}</div><div class="room-sub">${r.sub||''}</div></div></div>`:`<div class="room-title">${r.name}</div><div class="room-sub">${r.sub||''}</div>`;el.innerHTML=`${heading}<div class="room-pips">${basePipsMarkup(r)}</div>${r.capacity?`<div class="room-capacity">${r.capacity}</div>`:''}`;if(r.weapon){el.addEventListener('mouseenter',()=>{if(state.exterior)return;state.hovered={side,room:r,el};refreshVisuals()});el.addEventListener('mouseleave',()=>{state.hovered=null;refreshVisuals()})}return el}
function renderShips(){enemyGrid.innerHTML='';playerGrid.innerHTML='';enemyRooms.forEach(r=>enemyGrid.appendChild(makeRoom(r,'enemy')));playerRooms.forEach(r=>playerGrid.appendChild(makeRoom(r,'player')));enemyMastPips.innerHTML=basePipsMarkup(enemyMast);playerMastPips.innerHTML=basePipsMarkup(playerMast)}
function roomWidth(){const el=enemyGrid.querySelector('.room');return el?el.getBoundingClientRect().width:132}
function renderTrack(){const w=roomWidth();aft.disabled=state.offset<=state.min;fore.disabled=state.offset>=state.max;playerBlock.style.transform=`translateX(${(state.offset-INITIAL_OFFSET)*w}px)`;scale.innerHTML='';for(let i=state.min;i<=state.max;i++){const t=document.createElement('div');t.className='track-tick'+(i===state.offset?' active':'');scale.appendChild(t)}refreshVisuals()}
function entityElement(side,e){if(e.kind==='mast')return side==='enemy'?enemyMastEl:playerMastEl;const grid=side==='enemy'?enemyGrid:playerGrid;return grid.querySelector(`.room[data-id="${e.id}"]`)}
function entityById(side,id){if(side==='enemy')return id===enemyMast.id?enemyMast:enemyRooms.find(r=>r.id===id)||null;return id===playerMast.id?playerMast:playerRooms.find(r=>r.id===id)||null}
function sourceWorldCol(side,r){return side==='player'?state.offset+r.col:r.col}
function targetBaseWorld(side){return side==='player'?0:state.offset}
function targetsInRange(side,r){const w=weapons[r.weapon],sw=sourceWorldCol(side,r),rooms=side==='player'?enemyRooms:playerRooms,mast=side==='player'?enemyMast:playerMast,targets=rooms.filter(t=>Math.abs((side==='player'?t.col:state.offset+t.col)-sw)<=w.arc),mw=side==='player'?mast.col:state.offset+mast.col;if(Math.abs(mw-sw)<=w.arc)targets.push(mast);return targets}
function impactAtOffset(intent,offset){if(intent.lane==='mast')return offset+playerMast.col===intent.targetWorld?playerMast:null;return playerRooms.find(r=>r.row===intent.lane&&offset+r.col===intent.targetWorld)||null}
const currentImpact=i=>impactAtOffset(i,state.offset),originalImpact=i=>impactAtOffset(i,INITIAL_OFFSET),sourceForIntent=i=>enemyRooms.find(r=>r.id===i.sourceId);
function clearTransient(){svg.innerHTML='';document.querySelectorAll('.enemy-source-focus,.friendly-source-focus,.enemy-impact,.friendly-target,.source-active').forEach(el=>el.classList.remove('enemy-source-focus','friendly-source-focus','enemy-impact','friendly-target','source-active'))}
function buildPips(e,incoming=0,dodged=0){const slots=Array.from({length:e.max},(_,i)=>i<e.hp?'heart':'empty');let idx=e.hp-1;for(let i=0;i<incoming&&idx>=0;i++,idx--)slots[idx]='hit';for(let i=0;i<dodged&&idx>=0;i++,idx--)slots[idx]='evade';return slots.map(s=>s==='hit'?'<span class="hit" title="Incoming damage">✕</span>':s==='evade'?'<span class="evade-mark" title="Avoided by movement">↝</span>':s==='empty'?'<span class="empty-pip">·</span>':'<span>♥</span>').join('')}
function resetIntentUI(){document.querySelectorAll('.intent-stack').forEach(el=>el.remove());for(const r of playerRooms){const el=entityElement('player',r),p=el.querySelector('.room-pips');if(p)p.innerHTML=buildPips(r)}playerMastPips.innerHTML=buildPips(playerMast)}
function bindIntentChip(chip,intent){chip.addEventListener('mouseenter',e=>{e.stopPropagation();if(state.exterior)return;state.intentHover=intent;refreshVisuals()});chip.addEventListener('mouseleave',()=>{state.intentHover=null;refreshVisuals()})}
function renderIntentPreview(){resetIntentUI();const incoming=new Map(),dodged=new Map(),byTarget=new Map();for(const intent of enemyIntents){const actual=currentImpact(intent),original=originalImpact(intent);if(actual){incoming.set(actual.id,(incoming.get(actual.id)||0)+intent.damage);if(!byTarget.has(actual.id))byTarget.set(actual.id,[]);byTarget.get(actual.id).push(intent)}if(original&&(!actual||actual.id!==original.id))dodged.set(original.id,(dodged.get(original.id)||0)+intent.damage)}for(const r of playerRooms){const el=entityElement('player',r);el.querySelector('.room-pips').innerHTML=buildPips(r,incoming.get(r.id)||0,dodged.get(r.id)||0)}playerMastPips.innerHTML=buildPips(playerMast,incoming.get(playerMast.id)||0,dodged.get(playerMast.id)||0);for(const [id,intents] of byTarget){const target=entityById('player',id),el=entityElement('player',target);if(!el)continue;const stack=document.createElement('div');stack.className='intent-stack';for(const intent of intents){const src=sourceForIntent(intent),chip=document.createElement('div');chip.className='intent-chip';chip.title=`${weapons[src.weapon].name}: ${intent.damage} damage`;chip.innerHTML=glyphMarkup(src.weapon,src.instance,true);bindIntentChip(chip,intent);stack.appendChild(chip)}el.appendChild(stack)}}
function drawArc(side,r,sourceEl,mode){const grid=side==='player'?enemyGrid:playerGrid,mast=side==='player'?enemyMastEl:playerMastEl,first=grid.querySelector('.room');if(!first)return;const sr=stage.getBoundingClientRect(),src=sourceEl.getBoundingClientRect(),gr=grid.getBoundingClientRect(),mr=mast.getBoundingClientRect(),cw=first.getBoundingClientRect().width,w=weapons[r.weapon],sw=sourceWorldCol(side,r),base=targetBaseWorld(side),minX=gr.left-sr.left+(sw-w.arc-base)*cw,maxX=gr.left-sr.left+(sw+w.arc-base+1)*cw,minY=Math.min(gr.top,mr.top)-sr.top,maxY=gr.bottom-sr.top,sx=src.left+src.width/2-sr.left,sy=src.top+src.height/2-sr.top,above=sy<minY,nearY=above?minY:maxY,farY=above?maxY:minY,p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('points',[[sx,sy],[minX,nearY],[minX,farY],[maxX,farY],[maxX,nearY]].map(v=>v.join(',')).join(' '));p.setAttribute('class',`arc-path ${mode}`);svg.appendChild(p)}
function highlightEntity(side,e,cls){const el=entityElement(side,e);if(el)el.classList.add(cls)}
function showSingleArc(side,r,sourceEl){sourceEl.classList.add('source-active');drawArc(side,r,sourceEl,side==='enemy'?'enemy-single':'friendly-single');if(side==='enemy'){const intent=enemyIntents.find(i=>i.sourceId===r.id),impact=intent?currentImpact(intent):null;if(impact)highlightEntity('player',impact,'enemy-impact');weaponInfo.innerHTML=`${glyphMarkup(r.weapon,r.instance,true)} <span>${weapons[r.weapon].name}${r.instance?` ${r.instance}`:''}</span>`;targetInfo.textContent=impact?`Intent: ${intent.damage} damage to ${impact.name}`:'Intent: shot currently passes through empty space';return}for(const target of targetsInRange(side,r))highlightEntity('enemy',target,'friendly-target');weaponInfo.innerHTML=`${glyphMarkup(r.weapon,r.instance,true)} <span>${weapons[r.weapon].name}${r.instance?` ${r.instance}`:''}</span>`;targetInfo.textContent='Blue targets are currently in range'}
function showAllArcs(side){const rooms=side==='player'?playerRooms:enemyRooms,grid=side==='player'?playerGrid:enemyGrid;for(const r of rooms.filter(x=>x.weapon)){const el=grid.querySelector(`.room[data-id="${r.id}"]`);if(!el)continue;const focused=state.hovered&&state.hovered.side===side&&state.hovered.room.id===r.id;drawArc(side,r,el,focused?(side==='enemy'?'enemy-single':'friendly-single'):(side==='enemy'?'enemy-overview':'friendly-overview'))}if(side==='enemy'){for(const i of enemyIntents){const impact=currentImpact(i);if(impact)highlightEntity('player',impact,'enemy-impact')}weaponInfo.textContent='Enemy firing arcs';targetInfo.textContent='Red rooms are where the current intents will actually land'}else{weaponInfo.textContent='Friendly firing arcs';targetInfo.textContent='Hover one of your guns for exact legal targets'}}
function showIntentFocus(intent){const src=sourceForIntent(intent),srcEl=entityElement('enemy',src),impact=currentImpact(intent);if(srcEl){srcEl.classList.add('enemy-source-focus');drawArc('enemy',src,srcEl,'intent-focus')}if(impact)highlightEntity('player',impact,'enemy-impact');weaponInfo.innerHTML=`${glyphMarkup(src.weapon,src.instance,true)} <span>${weapons[src.weapon].name}${src.instance?` ${src.instance}`:''}</span>`;targetInfo.textContent=impact?`${intent.damage} damage will land on ${impact.name}`:'This shot is currently avoided by movement'}
function refreshVisuals(){clearTransient();renderIntentPreview();if(state.exterior){weaponInfo.textContent='Exterior view';targetInfo.textContent='Press H to return to targeting view';return}if(state.intentHover){showIntentFocus(state.intentHover);return}if(state.heldSide){showAllArcs(state.heldSide);return}if(state.hovered){showSingleArc(state.hovered.side,state.hovered.room,state.hovered.el);return}weaponInfo.textContent='None';targetInfo.textContent='Hover a cannon or an enemy intent icon.'}
function moveLeft(){if(state.offset>state.min){state.offset--;renderTrack()}}
function moveRight(){if(state.offset<state.max){state.offset++;renderTrack()}}
aft.onclick=moveLeft;fore.onclick=moveRight;
function toggleExterior(){state.exterior=!state.exterior;state.heldSide=null;state.hovered=null;state.intentHover=null;document.body.classList.toggle('exterior-mode',state.exterior);refreshVisuals()}
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='arrowleft'){e.preventDefault();if(!e.repeat)moveLeft();return}if(key==='arrowright'){e.preventDefault();if(!e.repeat)moveRight();return}if(e.repeat)return;if(key==='h'){toggleExterior();return}if(state.exterior)return;if(key==='z'){state.heldSide='enemy';refreshVisuals()}if(key==='x'){state.heldSide='player';refreshVisuals()}});
window.addEventListener('keyup',e=>{const key=e.key.toLowerCase();if((key==='z'&&state.heldSide==='enemy')||(key==='x'&&state.heldSide==='player')){state.heldSide=null;refreshVisuals()}});
window.addEventListener('blur',()=>{state.heldSide=null;state.intentHover=null;refreshVisuals()});window.addEventListener('resize',renderTrack);
renderShips();renderTrack();
