const weapons={standard:{name:'Standard Cannon',arc:1,detail:'Opposite + 1 adjacent'},heavy:{name:'Heavy Cannon',arc:1,detail:'Opposite + 1 adjacent'},long:{name:'Long Gun',arc:2,detail:'Opposite + 2 adjacent'},repeater:{name:'Repeater Cannon',arc:1,detail:'Opposite + 1 adjacent'}};
const enemyRooms=[{name:'Standard',sub:'Cannon',pips:'♥ ♥',weapon:'standard',row:0,col:0},{name:'Heavy',sub:'Cannon',pips:'♥ ♥ ♥ ♥',weapon:'heavy',row:0,col:1},{name:'Repeater',sub:'Cannon',pips:'♥ ♥ ♥',weapon:'repeater',row:0,col:2},{name:'Long Gun',sub:'',pips:'♥ ♥',weapon:'long',row:0,col:3},{name:'Unknown',sub:'',pips:'♥ ♥',row:1,col:0},{name:'Carpenter',sub:'',pips:'♥ ♥',row:1,col:1,capacity:'Timber 3/4'},{name:'Unknown',sub:'',pips:'♥ ♥',row:1,col:2},{name:'Hold',sub:'',pips:'♥ ♥',row:1,col:3,capacity:'Cargo 2/3'}];
const playerRooms=[{name:'Standard',sub:'Gun Deck',pips:'♥ ♥ ♥',weapon:'standard',row:0,col:0,capacity:'2 loaded'},{name:'Magazine',sub:'',pips:'♥ <span class="hit">✕</span>',row:0,col:1,capacity:'6 / 6'},{name:'Heavy',sub:'Gun Deck',pips:'♥ ♥ ♥',weapon:'heavy',row:0,col:2,capacity:'Ready'},{name:'General Hold',sub:'',pips:'♥ <span class="hit">✕</span>',row:1,col:0,capacity:'2 / 3'},{name:'Carpenter',sub:'',pips:'♥ ♥',row:1,col:1,capacity:'Timber 4/4'},{name:'General Hold',sub:'',pips:'♥ ♥',row:1,col:2,capacity:'1 / 3'}];
const state={offset:1,min:-2,max:4,hovered:null,heldSide:null};
const enemyGrid=document.getElementById('enemyGrid'),playerGrid=document.getElementById('playerGrid'),playerBlock=document.getElementById('playerBlock'),stage=document.getElementById('combatStage'),svg=document.getElementById('arcOverlay'),weaponInfo=document.getElementById('weaponInfo'),targetInfo=document.getElementById('targetInfo'),aft=document.getElementById('moveAft'),fore=document.getElementById('moveFore'),scale=document.getElementById('trackScale');
function makeRoom(r,side){const el=document.createElement('div');el.className='room'+(r.weapon?' weapon':'');el.dataset.side=side;el.dataset.col=r.col;el.dataset.row=r.row;if(r.weapon)el.dataset.weapon=r.weapon;el.innerHTML=`<div class="room-title">${r.name}</div><div class="room-sub">${r.sub||''}</div><div class="room-pips">${r.pips}</div>${r.capacity?`<div class="room-capacity">${r.capacity}</div>`:''}`;if(r.weapon){el.addEventListener('mouseenter',()=>{state.hovered={side,room:r,el};if(!state.heldSide)showSingleArc(side,r,el)});el.addEventListener('mouseleave',()=>{state.hovered=null;if(!state.heldSide)clearVisuals()})}return el}
function renderShips(){enemyRooms.forEach(r=>enemyGrid.appendChild(makeRoom(r,'enemy')));playerRooms.forEach(r=>playerGrid.appendChild(makeRoom(r,'player')))}
function roomWidth(){const el=enemyGrid.querySelector('.room');return el?el.getBoundingClientRect().width:132}
function renderTrack(){const w=roomWidth();aft.disabled=state.offset<=state.min;fore.disabled=state.offset>=state.max;playerBlock.style.transform=`translateX(${(state.offset-1)*w}px)`;scale.innerHTML='';for(let i=state.min;i<=state.max;i++){const t=document.createElement('div');t.className='track-tick'+(i===state.offset?' active':'');scale.appendChild(t)}refreshVisuals()}
function sourceWorldCol(side,room){return side==='player'?state.offset+room.col:room.col}
function targetBaseWorld(side){return side==='player'?0:state.offset}
function targetRooms(side,room){const w=weapons[room.weapon],sourceWorld=sourceWorldCol(side,room),rooms=side==='player'?enemyRooms:playerRooms;return rooms.filter(r=>{const targetWorld=side==='player'?r.col:state.offset+r.col;return Math.abs(targetWorld-sourceWorld)<=w.arc})}
function clearHighlights(){document.querySelectorAll('.room.targetable,.room.source-active').forEach(el=>el.classList.remove('targetable','source-active'))}
function clearVisuals(){clearHighlights();svg.innerHTML='';weaponInfo.textContent='None';targetInfo.textContent='Hover a cannon.'}
function highlightTargets(side,room){const targets=targetRooms(side,room),grid=side==='player'?enemyGrid:playerGrid;for(const t of targets){const el=grid.querySelector(`.room[data-col="${t.col}"][data-row="${t.row}"]`);if(el)el.classList.add('targetable')}return targets}
function drawTheoreticalArc(side,room,sourceEl,all=false){const targetGrid=side==='player'?enemyGrid:playerGrid;const firstTarget=targetGrid.querySelector('.room');if(!firstTarget)return;const sr=stage.getBoundingClientRect(),src=sourceEl.getBoundingClientRect(),gr=targetGrid.getBoundingClientRect(),cw=firstTarget.getBoundingClientRect().width,w=weapons[room.weapon],sourceWorld=sourceWorldCol(side,room),baseWorld=targetBaseWorld(side),minWorld=sourceWorld-w.arc,maxWorld=sourceWorld+w.arc,minX=gr.left-sr.left+(minWorld-baseWorld)*cw,maxX=gr.left-sr.left+(maxWorld-baseWorld+1)*cw,minY=gr.top-sr.top,maxY=gr.bottom-sr.top,sx=src.left+src.width/2-sr.left,sy=src.top+src.height/2-sr.top,above=sy<minY,nearY=above?minY:maxY,farY=above?maxY:minY;const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('points',[[sx,sy],[minX,nearY],[minX,farY],[maxX,farY],[maxX,nearY]].map(x=>x.join(',')).join(' '));p.setAttribute('class','arc-path'+(all?' all-arcs':''));svg.appendChild(p)}
function showSingleArc(side,room,sourceEl){clearVisuals();highlightTargets(side,room);sourceEl.classList.add('source-active');drawTheoreticalArc(side,room,sourceEl,false);const w=weapons[room.weapon],targets=targetRooms(side,room),cols=[...new Set(targets.map(t=>t.col+1))].sort((a,b)=>a-b);weaponInfo.textContent=`${w.name} — ${w.detail}`;targetInfo.textContent=cols.length?`Columns ${cols.join(', ')}`:'No legal targets at this alignment.'}
function showAllArcs(side){clearVisuals();const rooms=side==='player'?playerRooms:enemyRooms,grid=side==='player'?playerGrid:enemyGrid;for(const r of rooms.filter(r=>r.weapon)){const sourceEl=grid.querySelector(`.room[data-col="${r.col}"][data-row="${r.row}"]`);if(!sourceEl)continue;sourceEl.classList.add('source-active');highlightTargets(side,r);drawTheoreticalArc(side,r,sourceEl,true)}weaponInfo.textContent=side==='player'?'All friendly firing arcs':'All enemy firing arcs';targetInfo.textContent=side==='player'?'Hold E to inspect':'Hold Q to inspect'}
function refreshVisuals(){if(state.heldSide){showAllArcs(state.heldSide);return}if(state.hovered){showSingleArc(state.hovered.side,state.hovered.room,state.hovered.el);return}clearVisuals()}
aft.onclick=()=>{if(state.offset>state.min){state.offset--;renderTrack()}};fore.onclick=()=>{if(state.offset<state.max){state.offset++;renderTrack()}};
window.addEventListener('keydown',e=>{if(e.repeat)return;const key=e.key.toLowerCase();if(key==='q'){state.heldSide='enemy';showAllArcs('enemy')}if(key==='e'){state.heldSide='player';showAllArcs('player')}});
window.addEventListener('keyup',e=>{const key=e.key.toLowerCase();if((key==='q'&&state.heldSide==='enemy')||(key==='e'&&state.heldSide==='player')){state.heldSide=null;refreshVisuals()}});
window.addEventListener('blur',()=>{state.heldSide=null;refreshVisuals()});
window.addEventListener('resize',()=>{renderTrack()});
renderShips();renderTrack();