const weapons={standard:{name:'Standard Cannon',arc:1,detail:'Opposite + 1 adjacent'},heavy:{name:'Heavy Cannon',arc:1,detail:'Opposite + 1 adjacent'},long:{name:'Long Gun',arc:2,detail:'Opposite + 2 adjacent'},repeater:{name:'Repeater Cannon',arc:1,detail:'Opposite + 1 adjacent'}};
const enemyRooms=[{name:'Standard',sub:'Cannon',pips:'♥ ♥',weapon:'standard',row:0,col:0},{name:'Heavy',sub:'Cannon',pips:'♥ ♥ ♥ ♥',weapon:'heavy',row:0,col:1},{name:'Repeater',sub:'Cannon',pips:'♥ ♥ ♥',weapon:'repeater',row:0,col:2},{name:'Long Gun',sub:'',pips:'♥ ♥',weapon:'long',row:0,col:3},{name:'Unknown',sub:'',pips:'♥ ♥',row:1,col:0},{name:'Carpenter',sub:'',pips:'♥ ♥',row:1,col:1,capacity:'Timber 3/4'},{name:'Unknown',sub:'',pips:'♥ ♥',row:1,col:2},{name:'Hold',sub:'',pips:'♥ ♥',row:1,col:3,capacity:'Cargo 2/3'}];
const playerRooms=[{name:'Standard',sub:'Gun Deck',pips:'♥ ♥ ♥',weapon:'standard',row:0,col:0,capacity:'2 loaded'},{name:'Magazine',sub:'',pips:'♥ <span class="hit">✕</span>',row:0,col:1,capacity:'6 / 6'},{name:'Heavy',sub:'Gun Deck',pips:'♥ ♥ ♥',weapon:'heavy',row:0,col:2,capacity:'Ready'},{name:'General Hold',sub:'',pips:'♥ <span class="hit">✕</span>',row:1,col:0,capacity:'2 / 3'},{name:'Carpenter',sub:'',pips:'♥ ♥',row:1,col:1,capacity:'Timber 4/4'},{name:'General Hold',sub:'',pips:'♥ ♥',row:1,col:2,capacity:'1 / 3'}];
const state={offset:1,min:-2,max:3,hovered:null};
const enemyGrid=document.getElementById('enemyGrid'),playerGrid=document.getElementById('playerGrid'),playerBlock=document.getElementById('playerBlock'),stage=document.getElementById('combatStage'),svg=document.getElementById('arcOverlay'),weaponInfo=document.getElementById('weaponInfo'),targetInfo=document.getElementById('targetInfo'),readout=document.getElementById('trackReadout'),aft=document.getElementById('moveAft'),fore=document.getElementById('moveFore'),scale=document.getElementById('trackScale');
function makeRoom(r,side){const el=document.createElement('div');el.className='room'+(r.weapon?' weapon':'');el.dataset.side=side;el.dataset.col=r.col;el.dataset.row=r.row;if(r.weapon)el.dataset.weapon=r.weapon;el.innerHTML=`<div class="room-title">${r.name}</div><div class="room-sub">${r.sub||''}</div><div class="room-pips">${r.pips}</div>${r.capacity?`<div class="room-capacity">${r.capacity}</div>`:''}`;if(r.weapon){el.addEventListener('mouseenter',()=>showArc(side,r,el));el.addEventListener('mouseleave',clearArc)}return el}
function renderShips(){enemyRooms.forEach(r=>enemyGrid.appendChild(makeRoom(r,'enemy')));playerRooms.forEach(r=>playerGrid.appendChild(makeRoom(r,'player')))}
function alignmentName(o){return({[-2]:'Aft 3',[-1]:'Aft 2',[0]:'Aft 1',[1]:'Broadside',[2]:'Fore 1',[3]:'Fore 2'})[o]||`Offset ${o}`}
function renderTrack(){readout.textContent=alignmentName(state.offset);aft.disabled=state.offset<=state.min;fore.disabled=state.offset>=state.max;playerBlock.style.transform=`translateX(${(state.offset-1)*148}px)`;scale.innerHTML='';for(let i=-2;i<=4;i++){const t=document.createElement('div');t.className='track-tick'+(i===state.offset?' active':'');scale.appendChild(t)}if(state.hovered)showArc(state.hovered.side,state.hovered.room,state.hovered.el,true)}
function targetRooms(side,room){const w=weapons[room.weapon];const sourceWorld=side==='player'?state.offset+room.col:room.col;const rooms=side==='player'?enemyRooms:playerRooms;return rooms.filter(r=>{const tw=side==='player'?r.col:state.offset+r.col;return Math.abs(tw-sourceWorld)<=w.arc})}
function clearHighlights(){document.querySelectorAll('.room.targetable').forEach(el=>el.classList.remove('targetable'))}
function showArc(side,room,sourceEl){state.hovered={side,room,el:sourceEl};clearHighlights();const targets=targetRooms(side,room),grid=side==='player'?enemyGrid:playerGrid;const els=[];for(const t of targets){const el=grid.querySelector(`.room[data-col="${t.col}"][data-row="${t.row}"]`);if(el){el.classList.add('targetable');els.push(el)}}drawArc(sourceEl,els);const w=weapons[room.weapon];weaponInfo.textContent=`${w.name} — ${w.detail}`;const cols=[...new Set(targets.map(t=>t.col+1))].sort((a,b)=>a-b);targetInfo.textContent=cols.length?`Columns ${cols.join(', ')}`:'No legal targets at this alignment.'}
function clearArc(){state.hovered=null;clearHighlights();svg.innerHTML='';weaponInfo.textContent='None';targetInfo.textContent='Hover a cannon.'}
function drawArc(sourceEl,targetEls){svg.innerHTML='';if(!targetEls.length)return;const sr=stage.getBoundingClientRect(),src=sourceEl.getBoundingClientRect(),rs=targetEls.map(e=>e.getBoundingClientRect());const minX=Math.min(...rs.map(r=>r.left))-sr.left,maxX=Math.max(...rs.map(r=>r.right))-sr.left,minY=Math.min(...rs.map(r=>r.top))-sr.top,maxY=Math.max(...rs.map(r=>r.bottom))-sr.top,sx=src.left+src.width/2-sr.left,sy=src.top+src.height/2-sr.top,above=sy<minY,nearY=above?minY:maxY,farY=above?maxY:minY;const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('points',[[sx,sy],[minX,nearY],[minX,farY],[maxX,farY],[maxX,nearY]].map(x=>x.join(',')).join(' '));p.setAttribute('class','arc-path');svg.appendChild(p)}
aft.onclick=()=>{if(state.offset>state.min){state.offset--;renderTrack()}};fore.onclick=()=>{if(state.offset<state.max){state.offset++;renderTrack()}};window.addEventListener('resize',()=>state.hovered&&showArc(state.hovered.side,state.hovered.room,state.hovered.el));renderShips();renderTrack();