const weapons={standard:{name:'Standard Cannon',arc:1,detail:'Opposite + 1 adjacent'},heavy:{name:'Heavy Cannon',arc:1,detail:'Opposite + 1 adjacent'},long:{name:'Long Gun',arc:2,detail:'Opposite + 2 adjacent'},repeater:{name:'Repeater Cannon',arc:1,detail:'Opposite + 1 adjacent'},chain:{name:'Chain Shot',arc:0,detail:'Opposite only · strong vs mast'}};
const weaponGlyphs={standard:`<svg viewBox="0 0 32 18"><circle cx="8" cy="9" r="3" fill="currentColor" stroke="none"/><path d="M13 9h13M22 5l4 4-4 4"/></svg>`,heavy:`<svg viewBox="0 0 32 18"><path d="M7 9l5-5 5 5-5 5-5-5z" fill="currentColor" stroke="none"/><path d="M19 4l7 5-7 5M20 9h7"/></svg>`,long:`<svg viewBox="0 0 32 18"><circle cx="8" cy="9" r="4"/><path d="M8 2v14M1 9h14M14 9h14M25 6l3 3-3 3"/></svg>`,repeater:`<svg viewBox="0 0 32 18"><circle cx="7" cy="5" r="2.2" fill="currentColor" stroke="none"/><circle cx="7" cy="9" r="2.2" fill="currentColor" stroke="none"/><circle cx="7" cy="13" r="2.2" fill="currentColor" stroke="none"/><path d="M12 5h12M12 9h15M12 13h12"/></svg>`,chain:`<svg viewBox="0 0 32 18"><circle cx="7" cy="9" r="4" fill="currentColor" stroke="none"/><circle cx="25" cy="9" r="4" fill="currentColor" stroke="none"/><path d="M11 8c4-4 6 6 10 2M11 11c4 4 6-6 10-2"/></svg>`};
const enemyRooms=[{id:'e-standard',name:'Standard',sub:'Cannon',hp:2,max:2,weapon:'standard',row:0,col:0},{id:'e-heavy',name:'Heavy',sub:'Cannon',hp:4,max:4,weapon:'heavy',row:0,col:1},{id:'e-repeater',name:'Repeater',sub:'Cannon',hp:3,max:3,weapon:'repeater',row:0,col:2},{id:'e-long',name:'Long Gun',sub:'',hp:2,max:2,weapon:'long',row:0,col:3},{id:'e-unknown-a',name:'Unknown',sub:'',hp:2,max:2,row:1,col:0},{id:'e-carpenter',name:'Carpenter',sub:'',hp:2,max:2,row:1,col:1,capacity:'Timber 3/4'},{id:'e-unknown-b',name:'Unknown',sub:'',hp:2,max:2,row:1,col:2},{id:'e-hold',name:'Hold',sub:'',hp:2,max:2,row:1,col:3,capacity:'Cargo 2/3'}];
const playerRooms=[{id:'p-standard',name:'Standard',sub:'Gun Deck',hp:3,max:3,weapon:'standard',row:0,col:0,capacity:'2 loaded'},{id:'p-mag',name:'Magazine',sub:'',hp:2,max:2,row:0,col:1,capacity:'6 / 6'},{id:'p-heavy',name:'Heavy',sub:'Gun Deck',hp:3,max:3,weapon:'heavy',row:0,col:2,capacity:'Ready'},{id:'p-hold-left',name:'General Hold',sub:'',hp:2,max:2,row:1,col:0,capacity:'2 / 3'},{id:'p-carp',name:'Carpenter',sub:'',hp:2,max:2,row:1,col:1,capacity:'Timber 4/4'},{id:'p-hold-right',name:'General Hold',sub:'',hp:2,max:2,row:1,col:2,capacity:'1 / 3'}];
const enemyMast={id:'e-mast',kind:'mast',name:'Mast',hp:3,max:3,col:1},playerMast={id:'p-mast',kind:'mast',name:'Mast',hp:3,max:3,col:1};
function assignWeaponInstances(rooms){const totals={},seen={};for(const r of rooms)if(r.weapon)totals[r.weapon]=(totals[r.weapon]||0)+1;for(const r of rooms){if(!r.weapon)continue;seen[r.weapon]=(seen[r.weapon]||0)+1;r.instance=totals[r.weapon]>1?String.fromCharCode(64+seen[r.weapon]):''}}
assignWeaponInstances(enemyRooms);assignWeaponInstances(playerRooms);
const INITIAL_OFFSET=1;
const enemyIntents=[{id:'i-standard',sourceId:'e-standard',targetWorld:1,lane:1,damage:1},{id:'i-heavy',sourceId:'e-heavy',targetWorld:2,lane:0,damage:2},{id:'i-repeater',sourceId:'e-repeater',targetWorld:3,lane:0,damage:1},{id:'i-long',sourceId:'e-long',targetWorld:2,lane:1,damage:1}];
